### ISSUE TITLE
Src code

### ISSUE THREAD

**Issue by furax124** [codeuk/klimt#2]
Bro Its 10 stars share it plz and add telegram exodus Metamask and steam Minecraft stealer

**Comment by codeuk** [comment]
I've already stated that I'm working on releasing the source code now. The reason it's not yet been released is because I'm adding a FileZilla server credential stealer among a few other stealing features (Telegram and Steam session stealers, Browser injection, extension stealer, etc.). Some may stay in the free version and some may be unique to the paid stealer.

Thanks.
